name: CI with Linux

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          tag: "processing-1292-4.2"
      - run: pwd
      - run: echo $PATH
      - run: ls -lah /opt/hostedtoolcache/
      - run: ls -lah /opt/hostedtoolcache/processing
      - run: ls -lah /opt/hostedtoolcache/processing/1292.0.0
      - run: ls -lah /opt/hostedtoolcache/processing/1292.0.0/x64
      - run: which processing
      - run: which processing-java
      - run: processing-java --help
      - run: processing --help
