name: CI with MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        version: '3.5.4'
        platform-filetype: 'macosx.zip'

  test:
    needs: build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        version: '3.5.4'
        platform-filetype: 'macosx.zip'
    - run: which -a Processing
    - run: Processing --help
    - run: which -a processing-java
    - run: processing-java --help
      