name: CI with MacOS

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          tag: "processing-1292-4.2"
      - run: which -a processing
      - run: which -a processing-java
      - run: processing --help
      - run: processing-java --help
