name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.3.0
      with:
        java-version: 11
    - uses: ./
    - run: pwd
    - run: echo $PATH
    - run: which processing
    - run: which processing-java